language: android

before_install:
  - chmod +x gradlew
  - chmod +x .buildscript/run_unit_test.sh
  - chmod +x .buildscript/deploy_snapshot.sh

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

after_success:
  - .buildscript/run_unit_test.sh
  - .buildscript/deploy_snapshot.sh

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

env:
  global:
    - secure: pEYwCsRKrAnj3jjzJij4Bwk+xndCRpshHNSlTM39j1lFLyo3WvMrewPEXMVqSvJZjVyktIPBJ9NNb96Tpy0dfNTFbfAp4Wjf1kOdxOWcDYlWLIrS/eSMAq7wXus02BJq7QC8qsHQJmhZ7Sj6b2HZYqoa9SBBbLOBew9XBznRx3/FxsSq9wG5j6lekkmuJjzlYnKA5cl4Fe9c884W2ug5tris6WHHBbgO16kj4RVrqtg9B80D3yyJnj4cBug8wp2EGEX3U1TOzvp+xvgHWztdOFQ3b7M1Q/sCrjAlGhH0cA+CLKqLbLJUWLtPz1qU2nSSYPtD2gaPO6Yg1M9q5JNGMxqh8tr5U292CY5HQgLOkb8ItJC9AcZ0ltOyffeuRLNo3aeq+l9MqD60gTboeP3C2WQRE7HIRm8Q289TtsqxQadrgjcg9T/6GHM9RusgTMyDuKPqOQhmp9KURGe92RzvysSd4CME7SoZnPAP7M/O877UOYFAED7EBMMhtMLHwopQjAagrfKxQoNs4qTW56ZjNUY7mwfVLZxfM5nuOX+cjdctEyFH73IZLb6a1cRtRajTFoLNHFamOvfUnGYRS3A/akTQNki7fBTuxkC5U9VPEurkFrrv2fU2ziOjboOkkRD+/e6BHhrhBeBTBvqhU3n4KzUITeJHHve9Xz57vgJ+T+I=
    - secure: CcaUbnEwJeTZNdP6PSDjnFH7ZszPxGgRphcCt7caZK0bJxOil+KqddMMQAW94UaKOLbd6jP/NBkASgvf8KokluQVGSXG/EEtRGf1d4tIDcv71/MNPDQwMTyTdCOvIm35oaCEz7/R2wpXzvbbOjyw5Xi/j6FSQ8CS0JNiMbrC5VgxaEhkKMXroV0eLK2TwW90PjORpCkkoCBcmhfyYMDHnNfr/lePD8PFxwSvmRz9dPTBKj839yunkInstAmO9AgT38KfJQG9yBWaq+jg0KvQJpGCAeDCPplue+9axYzsSgkPliQh9gnRCDUA7+F150uasuJwjiTBMVCYaEnK9lL+TawX2Rswx6KFJr/krBN/9B3yajmL1YlkkJonFJ6IpAqrfGGJNdbnWNRWtLrn86pMjJC69kPDvJOn9Yy7l7+3qa/cAaNGOfoBrVU+iZj9AeTcAX3ZlWV219xaj6RE3SFUDALvr+MvHnonvkwGbP4+Kwe4ioLaG7L/ZYIrLK7x6K0KFszbPoERUdJqRYzNfzi2/AueIdwJx9m2oGn/dRoQrBzsSRo98fx7UGziOkyXsUkx9WqcNlw7VLNW7DqIV921Dip7jeAt5kMmjDZ/KNP9ewOJI1Fw7mqfsspsFpY+V5h5x+4CnlHvHsFSyZZEQwjmIXbC1pUgcAz+M8OYPIsEfMI=

